import catalog from '@/data/starCatalog.json';

// ─────────────────────────────────────────────────────────────────────────────
// REAL STAR DATA
// ─────────────────────────────────────────────────────────────────────────────
// src/data/starCatalog.json is generated by cross-matching every star position
// in our IAU stick figures against the HYG database v3.8 (astronexus/HYG-
// Database), which merges the Hipparcos catalogue, the Yale Bright Star
// Catalogue and the Gliese catalogue of nearby stars.
//
// Every entry below is measured data: proper name / Bayer designation, HD and
// HIP identifiers, MK spectral type, Johnson V apparent magnitude, absolute
// magnitude and the parallax distance converted from parsecs to light-years.
// ─────────────────────────────────────────────────────────────────────────────

export interface CatalogStar {
  name: string;
  designation: string;
  hd: string | null;
  hip: string | null;
  spect: string | null;
  mag: number;
  absmag: number | null;
  distanceLy: number | null;
  con: string | null;
  /** Angular separation (deg) between chart position and catalogue position. */
  sep: number;
}

const CATALOG = catalog as unknown as Record<string, CatalogStar>;

/** Look up the real star behind a chart position, by constellation + index. */
export function lookupStar(abbr: string, index: number): CatalogStar | null {
  return CATALOG[`${abbr}:${index}`] ?? null;
}

/** Approximate photospheric colour for an MK spectral type. */
export function spectralColor(spect: string | null | undefined): string {
  const cls = (spect ?? '').trim().charAt(0).toUpperCase();
  switch (cls) {
    case 'O':
      return '#9bb0ff';
    case 'B':
      return '#aabfff';
    case 'A':
      return '#cad8ff';
    case 'F':
      return '#f8f7ff';
    case 'G':
      return '#ffedbe';
    case 'K':
      return '#ffd2a1';
    case 'M':
      return '#ff9a62';
    default:
      return '#e2e8f0';
  }
}

/** Plain-language description of a spectral class, for the HUD. */
export function spectralDescription(spect: string | null | undefined): string {
  const cls = (spect ?? '').trim().charAt(0).toUpperCase();
  const map: Record<string, string> = {
    O: 'Blue supergiant — extremely hot',
    B: 'Blue-white, very hot',
    A: 'White, hot',
    F: 'Yellow-white',
    G: 'Yellow, Sun-like',
    K: 'Orange, cooler than the Sun',
    M: 'Red, cool',
  };
  return map[cls] ?? 'Spectral class not catalogued';
}
