/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstellationsRouteImport } from './routes/constellations'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PlanetsSlugRouteImport } from './routes/planets.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationsRoute = ConstellationsRouteImport.update({
  id: '/constellations',
  path: '/constellations',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsSlugRoute = PlanetsSlugRouteImport.update({
  id: '/planets/$slug',
  path: '/planets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/timeline': typeof TimelineRoute
  '/planets/$slug': typeof PlanetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/timeline': typeof TimelineRoute
  '/planets/$slug': typeof PlanetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/timeline': typeof TimelineRoute
  '/planets/$slug': typeof PlanetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/constellations' | '/timeline' | '/planets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/constellations' | '/timeline' | '/planets/$slug'
  id: '__root__' | '/' | '/constellations' | '/timeline' | '/planets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstellationsRoute: typeof ConstellationsRoute
  TimelineRoute: typeof TimelineRoute
  PlanetsSlugRoute: typeof PlanetsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellations': {
      id: '/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof ConstellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/$slug': {
      id: '/planets/$slug'
      path: '/planets/$slug'
      fullPath: '/planets/$slug'
      preLoaderRoute: typeof PlanetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstellationsRoute: ConstellationsRoute,
  TimelineRoute: TimelineRoute,
  PlanetsSlugRoute: PlanetsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
